version: '{build}'
os: Visual Studio 2015
configuration: Release

before_build:
- ps: dotnet --version
- ps: dotnet restore

build:
  verbosity: minimal

build_script:
- ps: '& ".\build\runner.ps1" Package'

test_script: 
- ps: '& ".\build\runner.ps1" Test'

artifacts:
- path: src\**\bin\**\*.nupkg

deploy:
- provider: Environment
  name: Public Nuget
  on:
    branch: master